import { useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { analyzePlan, getQueryDetail, rewriteSql, type PlanAnalysis, type SQLRewriteResponse } from '../lib/api'
import { PlanVisualization } from '../components/PlanVisualization'
import { OptimizationFlowHeader } from '../components/OptimizationFlowHeader'
import { OptimizationTrace } from '../components/OptimizationTrace'

export function PlanViewer() {
  const [searchParams] = useSearchParams()
  const initialSql =
    searchParams.get('sql') ||
    "SELECT id, customer_id, amount FROM telemetry_demo_orders WHERE status = 'pending' ORDER BY created_at DESC LIMIT 50"
  const [sql, setSql] = useState(initialSql)
  const [analysis, setAnalysis] = useState<PlanAnalysis | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  // SQL AST Rewriter State
  const [rewriteResult, setRewriteResult] = useState<SQLRewriteResponse | null>(null)
  const [rewriting, setRewriting] = useState(false)
  const [rewriteError, setRewriteError] = useState<string | null>(null)

  const handleAnalyze = async (queryOverride?: unknown) => {
    const targetSql = typeof queryOverride === 'string' ? queryOverride : sql
    setLoading(true)
    setError(null)
    try {
      const res = await analyzePlan(targetSql.replace(/;\s*$/, ''))
      setAnalysis(res)
    } catch (err: any) {
      setError(err.message || 'Plan analysis failed. Only read-only SELECT / WITH queries are supported.')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    const qid = searchParams.get('queryId')
    const sqlParam = searchParams.get('sql')
    if (qid) {
      getQueryDetail(qid)
        .then((q) => {
          if (q.normalized_query) {
            const clean = q.normalized_query.replace(/;\s*$/, '')
            setSql(clean)
            handleAnalyze(clean)
          }
        })
        .catch(() => {
          handleAnalyze()
        })
    } else if (sqlParam) {
      const clean = sqlParam.replace(/;\s*$/, '')
      setSql(clean)
      handleAnalyze(clean)
    } else {
      handleAnalyze()
    }
  }, [searchParams])

  const handleRewrite = async () => {
    setRewriting(true)
    setRewriteError(null)
    setRewriteResult(null)
    try {
      const res = await rewriteSql(sql, true)
      setRewriteResult(res)
    } catch (err: any) {
      setRewriteError(err.message || 'SQL rewrite analysis failed.')
    } finally {
      setRewriting(false)
    }
  }

  const handleApplyRewritten = (newSql: string) => {
    setSql(newSql)
    handleAnalyze()
  }

  return (
    <section>
      <div className="section-head" style={{ marginBottom: '18px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '6px' }}>
          <span className="badge badge-observed">OBSERVED: PostgreSQL EXPLAIN</span>
          <span className="badge badge-ai-analysis">AI ANALYSIS: AST & Node Parser</span>
          <span className="badge badge-recommendation">Optimization Ready</span>
        </div>
        <h1 style={{ fontSize: '2.2rem', margin: 0 }}>Execution Plan Viewer & SQL Rewriter</h1>
        <p className="subtitle" style={{ fontSize: '0.95rem', color: '#64748b' }}>
          Interactive planner cost evaluation. Explains queries safely, transforms SQL ASTs, and maps plan bottlenecks to DBZenith optimizations.
        </p>
      </div>

      <OptimizationFlowHeader currentStage="analyze" />

      {/* Self-Explanatory Plan Explainer Banner */}
      <div className="guide-banner">
        <div className="guide-banner-icon">🌲</div>
        <div className="guide-banner-content">
          <div className="guide-banner-title">
            <span>POSTGRESQL PLAN TREE VISUALIZATION & AST REWRITES</span>
            <span className="badge badge-ai-analysis">STAGE 2: ANALYZE</span>
          </div>
          <p className="guide-banner-desc">
            Visualizes the hierarchical node tree generated by PostgreSQL's query optimizer. Red borders identify high-cost bottleneck operators (such as Sequential Scans and Nested Loops). Click <strong>"⚡ AST Query Rewriter"</strong> to automatically eliminate redundant DISTINCT clauses, optimize OR-to-IN chains, and remove redundant subquery orderings.
          </p>
        </div>
      </div>

      <article className="card section-card" style={{ marginBottom: '20px' }}>
        <label style={{ fontSize: '12px', fontWeight: 700, display: 'block', marginBottom: '8px' }}>
          SQL Statement (Read-only SELECT / WITH):
        </label>
        <textarea
          className="plan-input"
          value={sql}
          onChange={(e) => setSql(e.target.value)}
          rows={3}
          placeholder="Enter SELECT query to explain..."
        />
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '10px' }}>
          <div style={{ display: 'flex', gap: '10px' }}>
            <button
              className="primary-button"
              onClick={handleAnalyze}
              disabled={loading || !sql.trim()}
            >
              {loading ? 'Evaluating EXPLAIN Plan...' : 'Explain & Visualize Plan'}
            </button>
            <button
              className="secondary-button"
              onClick={handleRewrite}
              disabled={rewriting || !sql.trim()}
            >
              {rewriting ? 'Analyzing AST...' : '⚡ AST Query Rewriter'}
            </button>
          </div>
          <small className="muted">Read-only constraint enforced: DDL/DML statements are rejected.</small>
        </div>
      </article>

      {rewriteError && <div className="alert" style={{ background: 'rgba(239, 68, 68, 0.1)', color: '#fca5a5' }}>{rewriteError}</div>}

      {/* SQL AST Rewriter Output & Diff */}
      {rewriteResult && (
        <article className="card section-card" style={{ marginBottom: '20px', borderLeft: '4px solid #38bdf8' }}>
          <div className="section-heading" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' }}>
            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                <span className="badge badge-recommendation">AST REWRITER RESULT</span>
                <span className={`badge ${rewriteResult.safety_verdict === 'safe' ? 'badge-success' : 'badge-warning'}`}>
                  {rewriteResult.safety_verdict.toUpperCase()}
                </span>
                <span className="badge" style={{ background: '#1e293b', color: '#cbd5e1' }}>
                  Transformation: {rewriteResult.transformation}
                </span>
              </div>
              <p style={{ margin: '6px 0 0 0', color: '#94a3b8', fontSize: '0.85rem' }}>
                {rewriteResult.reason}
              </p>
            </div>
            {rewriteResult.rewritten_query && (
              <button
                className="btn btn-primary"
                style={{ fontSize: '12px', padding: '6px 12px' }}
                onClick={() => handleApplyRewritten(rewriteResult.rewritten_query!)}
              >
                Apply Rewritten SQL & Re-Explain →
              </button>
            )}
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '12px', marginBottom: '14px' }}>
            <div style={{ background: '#090d16', padding: '10px 14px', borderRadius: '4px' }}>
              <div style={{ fontSize: '0.75rem', color: '#94a3b8' }}>Cost Improvement:</div>
              <div style={{ fontSize: '1.2rem', fontWeight: 700, color: (rewriteResult.cost_improvement_pct ?? 0) > 0 ? '#10b981' : '#f8fafc' }}>
                {rewriteResult.cost_improvement_pct != null ? `${rewriteResult.cost_improvement_pct.toFixed(1)}%` : 'Evaluated'}
              </div>
            </div>
            <div style={{ background: '#090d16', padding: '10px 14px', borderRadius: '4px' }}>
              <div style={{ fontSize: '0.75rem', color: '#94a3b8' }}>Semantic Equivalence:</div>
              <div style={{ fontSize: '1.2rem', fontWeight: 700, color: rewriteResult.semantic_match ? '#10b981' : '#f59e0b' }}>
                {rewriteResult.semantic_match ? 'Verified ✓' : 'Conservative'}
              </div>
            </div>
            <div style={{ background: '#090d16', padding: '10px 14px', borderRadius: '4px' }}>
              <div style={{ fontSize: '0.75rem', color: '#94a3b8' }}>Sandbox Validation:</div>
              <div style={{ fontSize: '1.2rem', fontWeight: 700, color: '#38bdf8' }}>
                {rewriteResult.validation_status.toUpperCase()}
              </div>
            </div>
          </div>

          {rewriteResult.rewritten_query && (
            <div>
              <div style={{ fontSize: '0.8rem', fontWeight: 600, color: '#cbd5e1', marginBottom: '6px' }}>
                Rewritten Query Statement:
              </div>
              <pre className="sql-box" style={{ background: '#090d16', color: '#a78bfa', borderColor: '#334155' }}>
                {rewriteResult.rewritten_query}
              </pre>
            </div>
          )}
        </article>
      )}

      {error && <div className="alert">{error}</div>}

      {analysis && (
        <>
          <div className="grid metrics" style={{ gridTemplateColumns: 'repeat(4, minmax(0, 1fr))', gap: '14px', marginBottom: '20px' }}>
            <article className="card">
              <span className="badge badge-observed">OBSERVED</span>
              <h2 style={{ marginTop: '8px' }}>Total Cost</h2>
              <strong style={{ fontSize: '24px' }}>
                {analysis.features?.total_cost?.toFixed(2) ?? '—'}
              </strong>
              <p>Planner arbitrary cost units</p>
            </article>

            <article className="card">
              <span className="badge badge-observed">OBSERVED</span>
              <h2 style={{ marginTop: '8px' }}>Estimated Rows</h2>
              <strong style={{ fontSize: '24px' }}>
                {analysis.features?.total_rows?.toLocaleString() ?? '—'}
              </strong>
              <p>Cardinality estimation</p>
            </article>

            <article className="card">
              <span className="badge badge-ai-analysis">AI ANALYSIS</span>
              <h2 style={{ marginTop: '8px' }}>Seq Scan Fraction</h2>
              <strong style={{ fontSize: '24px', color: (analysis.features?.seq_scan_fraction ?? 0) > 0.4 ? '#b91c1c' : '#166534' }}>
                {((analysis.features?.seq_scan_fraction ?? 0) * 100).toFixed(1)}%
              </strong>
              <p>Unindexed table scan ratio</p>
            </article>

            <article className="card">
              <span className="badge badge-ai-analysis">AI ANALYSIS</span>
              <h2 style={{ marginTop: '8px' }}>Structural Hash</h2>
              <strong style={{ fontSize: '14px', fontFamily: 'monospace', wordBreak: 'break-all' }}>
                {analysis.structural_hash.slice(0, 16)}…
              </strong>
              <p>Invariant AST graph topology ID</p>
            </article>
          </div>

          <article className="card section-card" style={{ marginBottom: '20px' }}>
            <div className="section-heading" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
              <div>
                <h2 style={{ margin: 0 }}>Visual Execution Plan Tree</h2>
                <span className="muted">Hierarchical representation of operator nodes and child pipelines</span>
              </div>
              <span className="badge badge-observed">OBSERVED</span>
            </div>

            <PlanVisualization analysis={analysis} />
          </article>

          {/* Dedicated Optimization Trace for this execution plan */}
          <OptimizationTrace
            title="Plan Optimization Trace & Bottleneck Remediation"
            query={{
              normalized_query: sql,
              mean_exec_time_ms: 75.0,
              calls: 1,
            }}
            planAnalysis={analysis}
            initialExpanded={true}
          />
        </>
      )}
    </section>
  )
}
